version: '3.8'

services:
  service1:
    build:
      context: ./services/service1
      dockerfile: Dockerfile
    ports:
      - '<REDACTED>:<REDACTED>'
    environment:
      - NODE_ENV=development
      - PORT=<REDACTED>
      - DB_USERNAME=<REDACTED>
      - DB_PASSWORD=<REDACTED>
      - DB_HOST=<REDACTED>
      - DB_NAME=<REDACTED>
      - DB_PARAMS=<REDACTED>
    # depends_on:
    #   - mongo

  # service2:
  #   build:
  #     context: ./services/service2
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5002:5002'
  #   environment:
  #     - NODE_ENV=development
  #     - MONGO_URI=mongodb://mongo:27017/test
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo:4.4
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo-data:/data/db

# volumes:
#   mongo-data:
